spring.application.name=Business Operations Mini Platform
spring.datasource.url=jdbc:h2:file:./data/business-ops;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.servlet.multipart.max-request-size=256KB
spring.servlet.multipart.max-file-size=256KB
server.tomcat.max-http-form-post-size=262144
server.error.include-message=never
server.error.include-stacktrace=never
server.error.include-binding-errors=never

